export const  NEXT_ICON = require('../../assets/Icons/next.png')
export const  DELETE_ICON = require('../../assets/Icons/delete.png')
export const  ADD_ICON = require('../../assets/Icons/addIcon.png')
export const  DATE_ICON = require('../../assets/Icons/datePicker.png')
export const  TIME_ICON = require('../../assets/Icons/clock.png')